# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  # Gavin, 20200802: Removing on-push, because I only want PRs to trigger this job
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a one jobs, "deploy"
  build:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    # Gavin, 202008014: Moved this up from its own Deploy job into this job ()
    - name: Deploy
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
